language: go
go:
  - 1.2
  - 1.3
  - tip
install:
  - go get github.com/robertkrimen/otto
  - go get gopkg.in/fsnotify.v0
  - go get github.com/robfig/gettext/po
script:
  - go test github.com/robfig/soy/...
